### ISSUE TITLE
Update Slick to `3.4.x`

### ISSUE THREAD

**Issue by ptrdom** [apache/incubator-pekko-persistence-jdbc#109]
While updating dependencies on a project of mine I got an error from sbt about issues with mixing `3.3.x` and `3.4.x` versions of Slick. I assume it is because of potential binary incompatibility. Would it be beneficial to update Slick to `3.4.x` for this project?

**Comment by pjfanning** [comment]
A warning does not mean that it will fail. It is an indication that you should test the change before going into production. We don't plan on doing a special release of this project with Slick 3.4.

#43 will include an upgrade to Slick 3.5.0 - when that is released.

**Comment by ptrdom** [comment]
Understood, thank you!
