### ISSUE TITLE
come up with new release strategy

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-persistence-jdbc#11]
* will be based on what we end up doing in incubator-pekko
* will need to remove the release train docs
* and remove/replace RELEASING.md
* possibly replace https://github.com/akka/akka-persistence-jdbc/blob/master/.github/release-drafter.yml

**Comment by mdedetrich** [comment]
@pjfanning Can we close this issue? I believe this topic is being discussed in a more general manner on mailing list/issues on pekko core and any such decision we make would apply to every project and not just pekko-persistence-jdbc specifically.
