### ISSUE TITLE
replace use of deprecated statefulMapConcat

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-persistence-jdbc#114]
https://github.com/search?q=repo%3Aapache%2Fincubator-pekko-persistence-jdbc%20statefulMapConcat&type=code

any interest in taking this on @mdedetrich, @kerr ?

**Comment by mdedetrich** [comment]
Is this still relevant since we actually decided to undeprprecate it due to performance reasons?

**Comment by pjfanning** [comment]
statefulMapConcat deprecation has been undone
