### ISSUE TITLE
scala3 build issue

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-persistence-jdbc#124]
https://github.com/apache/incubator-pekko-persistence-jdbc/actions/runs/8190639534/job/22398044719

Seems like we need to fix the skip-packages setting - changed in Scala 3.

fyi @mdedetrich

**Comment by mdedetrich** [comment]
Hmm, according to the table it should be the same https://docs.scala-lang.org/scala3/guides/migration/scaladoc-settings-compatibility.html ?

**Comment by mdedetrich** [comment]
Aah I remember now, we also did this in pekko-http, fixing now
