### ISSUE TITLE
need to review if we can remove ojdbc6 jar

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-persistence-jdbc#8]
* see https://github.com/apache/incubator-pekko-persistence-jdbc/tree/main/core/lib
* we should not have jars checked in
* we can get the build to script to download the jar from an external web site, if necessary

**Comment by mdedetrich** [comment]
@pjfanning Is this just used for testing? If so we can use testcontainers which has an oracle image and that way I don't think we will be breaking any licensing.

**Comment by pjfanning** [comment]
@mdedetrich I haven't investigated why the jar is checked in. It is likely to be there for testing. We can not release a source release that includes this jar.
* we can include binaries in source releases
* I believe that this jar in particular has a license that is not compatible with Apache's

**Comment by pjfanning** [comment]
We must support a source release - ASF requirements.

We can obviously do something with sbt-source-dist to exclude jars. But then any attempt to run the build after unzipping the source zip will be liable to fail because of the missing jar.

One solution is simply to remove the jar from git altogetehr and to rewrite the build script so that it downloods the ojdbc jar. I do not know why this jar isn't currently downloaded using libraryDependencies in the sbt files already.

**Comment by mdedetrich** [comment]
PR made here https://github.com/apache/incubator-pekko-persistence-jdbc/pull/32
