### ISSUE TITLE
Upgrade Slick to 3.4.1

### ISSUE THREAD

**Issue by cptwunderlich** [apache/incubator-pekko-persistence-jdbc#93]
Please release a version of pekko-persistence-jdbc with the Slick dependency updated to v3.4.1.
Rationale: the last few [Play versions](https://github.com/playframework/play-slick) are on this version, we are using it and get a version conflict with the version used in pekko.

I am aware of the discussion regarding Slick 3.5, but the last messages I saw were from August 2023. Now it is December 2023, Slick 3.5 is still not released (AFAIK waiting for 2 packages in the ecosystem). So while waiting for Slick 3.5 w. Scala 3, which has an unknown timeline, a release with 3.4.1 would enable everyone to use the last Slick version with the last Play version without any version conflicts.

I tried updating it locally and it seems to work without issue. I'll gladly open a PR if this proposal is acceptable to you.

**Comment by pjfanning** [comment]
I'm afraid you are going to have to set your build script up to force the use of the slick version you want.

**Comment by cptwunderlich** [comment]
OK, I see that it is compatible, so no problem here. Thx.
